name: Run e2e

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.JS
      uses: actions/setup-node@master
    - run: brew tap wix/brew
    - run: brew install applesimutils
    - run: yarn install --frozen-lockfile
  test:
    runs-on: macos-latest
    steps:
    - run: yarn detox build --configuration ios
    - run: yarn detox test  --configuration ios --cleanup
