name: Run unit test's

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.JS
      uses: actions/setup-node@master
    - run: yarn install --frozen-lockfile
    - run: yarn jest --ci
  e2e:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.JS
      uses: actions/setup-node@master
      # TODO: uncomment when build is will be successful
    # - run: brew tap wix/brew
    # - run: brew install applesimutils
    - run: yarn install --frozen-lockfile
    - run: pod install
      working-directory: ios

    - run: xcodebuild clean archive -workspace meditationapp.xcworkspace -scheme MeditationApp -archivePath MeditationApp.xcarchive CODE_SIGNING_ALLOWED=NO | xcpretty
      working-directory: ios

    # - run: yarn detox build --configuration ios.sim.release
    # - run: yarn detox test  --configuration ios.sim.release --cleanup

